### ISSUE TITLE
DiscordAPIError[50027]: Invalid Webhook Token

### ISSUE THREAD

**Issue by muralianand12345** [sl34x/ticket-bot#2]
When trying to Delete and Archive this error occurs.

```
C:\Users\smura\Desktop\ticket-bot-main\node_modules\@discordjs\rest\dist\index.js:748
        throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
              ^

DiscordAPIError[50027]: Invalid Webhook Token
    at SequentialHandler.runRequest (C:\Users\smura\Desktop\ticket-bot-main\node_modules\@discordjs\rest\dist\index.js:748:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\smura\Desktop\ticket-bot-main\node_modules\@discordjs\rest\dist\index.js:560:14)
    at async REST.request (C:\Users\smura\Desktop\ticket-bot-main\node_modules\@discordjs\rest\dist\index.js:1000:22)
    at async InteractionWebhook.send (C:\Users\smura\Desktop\ticket-bot-main\node_modules\discord.js\src\structures\Webhook.js:213:15) {
  rawError: { message: 'Invalid Webhook Token', code: 50027 },
  code: 50027,
  status: 401,
  method: 'POST',
  url: 'https://discord.com/api/v10/webhooks/942080467241410630/aW50ZXJhY3Rpb246MTAwMDA2NzU3ODc3OTE0NDIyMjpZR0FZUHdKZHllUmtZMGJVb01jSTRUNlo0VEpjQkhuaGxqcndna3FQQ0xrdk9TcVUySnVvMTB5MmpzMDlSTmQyMUZUeGR1TWNBb1hxRHdUQ2pLRHg5dXZSQ3lvd2E1RnlsUzYyMTJUVmNJVk1NaFM1bEtIWldaOEp1S0MzaXR1VA?wait=true',
  requestBody: {
    files: [],
    json: {
      content: 'Ticket successfully archived.',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: 64,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    }
  }
}

```

**Comment by sl34x** [comment]
Discord bug, it can be fixed after a while.

**Comment by sl34x** [comment]
The problem seems to be solved 😊
